# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            閒燴
tagline:          Yummies From Scratch
description:      悠閒烹飪著健康喜愛的食物給親朋好友是一種溫馨的幸福
avatar:           https://photos.smugmug.com/Yummiesfromscratch/i-QK4c77B/0/O/totoro-128x128.jpg
url:              https://www.yummiesfromscratch.com

author:
  name:           Serena Li
  url:            https://twitter.com/totoro538

paginate:         5

excerpt_separator: "\n\n\n"

exclude: ["vendor"]

# Custom vars
