# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            閒燴
tagline:          'Yummies From Scratch'
description:      '悠閒烹飪著健康喜愛的食物給親朋好友是一種溫馨的幸福'
url:              http://www.yummiesfromscratch.com
baseurl:          /

author:
  name:           'Serena Li'
  url:            https://twitter.com/totoro538

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://github.com/yummiesfromscratch/yummiesfromscratch.github.io
