# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            閒燴
tagline:          Yummies From Scratch
description:      悠閒烹飪著健康喜愛的食物給親朋好友是一種溫馨的幸福
avatar:           http://38.media.tumblr.com/avatar_69864b944d93_128.png
url:              http://www.yummiesfromscratch.com
baseurl:          /

author:
  name:           Serena Li
  url:            https://twitter.com/totoro538

paginate:         5

excerpt_separator: "\n\n\n"

# Custom vars
